apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
  labels:
    app: website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
        - name: website
          image: hub.ziemba.net/website:V0.0.1
          ports:
            - containerPort: 80
              hostPort: 80
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: website
spec:
  selector:
    app: website
  ports:
    - name: website-test
      protocol: TCP
      port: 80
      targetPort: 80
